/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

public class Library implements RequestHandler<Integer, String> {
    @Override
    public String handleRequest(Integer input, Context context) {
        return "Hello, World";
    }
}